### ISSUE TITLE
validation at `validate` or `plan` phase

### ISSUE THREAD

**Issue by finkinfridom** [tlkamp/terraform-provider-validation#23]
hey @tlkamp , 
I found your repo because we were looking for a possibility to inform our integrators that some variable is deprecated/obsolete or, generally speaking, not be used anymore.

It seems a great implementation but I just noticed that the provider only works at apply time.
Do you think it would be possible to have (as other providers do), a validation process to occur before?

**Comment by tlkamp** [comment]
@finkinfridom Can you describe your use of the provider? There are data sources that you can use to evaluate the validation at plan time.

**Comment by finkinfridom** [comment]
thanks for replying so quickly :)

We have a set of versioned internal common modules we reuse across different projects.
Trying to stick to semantic versioning as much as possible, we marked some variables as `deprecated` or `obsolete` over time.

At the moment we're identifying those scenarios in the variable `description` property but, indeed, it's not enough as we have legacy projects that used those variables and people don't have a look at the description only.

Digging the Terraform documentation I cannot find something useful for our purposes, as the `check` keyword applies to `data` and `resources` only while we need something in an earlier stage.

I just tried this approach (as reading your medium post and some more info in the provider documentation)

```

data "validation_warnings" "azureshares" {
  warning {
    condition = length(var.azureshares) > 0
    summary   = "var.azureshares is deprecated"
    details   = "Please use 'azure_file_shares' instead"
  }
}
```

but when trying the `terraform plan` command, no `warning` is spawned even if the `condition` is evaluated as `true`

In my mind, the final result should appear similar to what other providers do such as

<img width="578" alt="image" src="https://github.com/tlkamp/terraform-provider-validation/assets/6241121/8a5b8e12-d0e4-484e-9b1d-f3b6ec42aac1">


Am I wrong or missing something?
thanks again

**Comment by tlkamp** [comment]
Thanks for the additional information!

I wrote this code as a minimal reproduction test case, which is working for me. I've included a screenshot below of what I'm seeing. If you're still not able to get this result I'll need a more complete example of the code you're using.

```hcl
terraform {
  required_providers {
    validation = {
      source  = "tlkamp/validation"
      version = "~> 1.0"
    }
  }
}

variable "azureshares" {
  type = list(string)
}


data "validation_warnings" "azureshares" {
  warning {
    condition = length(var.azureshares) > 0
    summary   = "var.azureshares is deprecated"
    details   = "Please use 'azure_file_shares' instead"
  }
}
```

![image](https://github.com/tlkamp/terraform-provider-validation/assets/18516698/65177c5f-8970-4e6b-84b8-b93cc11bd3e0)

**Comment by tlkamp** [comment]
For completeness, this is the output I get when I set the value of `var.azureshares` to an empty list:

![image](https://github.com/tlkamp/terraform-provider-validation/assets/18516698/9bd5e358-bab2-40e5-896f-2014cc2b31d8)

**Comment by finkinfridom** [comment]
I just noticed this information from the `terraform plan` operation

<img width="711" alt="image" src="https://github.com/tlkamp/terraform-provider-validation/assets/6241121/10c3f7a8-a0aa-45d6-8589-c61843a30920">


The `validation` block will be part of a module that could have additional resources to be created.
So, in the case it's the first time I'm using this module (e.g. creating the resources) and I'm also providing the deprecated variable, nothing will show up. From the second `tf plan` operation, I should see the warning.
Do you think, it's something that could be "fixed" on the provider side?

**Comment by tlkamp** [comment]
I made some changes to my reproduction test case to include creating resources and I wasn't able to reproduce this result. Are you using a value that is only known at `terraform apply` time? If so, the only way to "fix" that is to reduce the dependencies in your code to values that will be known at plan time. That isn't something the provider can work around; it is controlled by Terraform core and when Terraform can know the values it is given as input.

If you can't make the value known at plan time, you can swap to using the `resource` instead of the `data` block (or you can use both).

I did also see that [HashiCorp is adding extended validation in an upcoming release](https://github.com/hashicorp/terraform/releases/tag/v1.9.0-beta1), which may not have the same limitation this one has.

Directory structure:
```console
.
├── main.tf
└── modules
    └── repro
        └── main.tf

2 directories, 2 files
```

`modules/repro/main.tf` contents:
```hcl
terraform {
  required_providers {
    validation = {
      source  = "tlkamp/validation"
      version = "~> 1.0"
    }
  }
}

variable "azureshares" {
  type = list(string)
}


data "validation_warnings" "azureshares" {
  warning {
    condition = length(var.azureshares) > 0
    summary   = "var.azureshares is deprecated"
    details   = "Please use 'azure_file_shares' instead"
  }
}

resource "local_file" "file" {
  filename = "test.txt"
  content  = join(" - ", var.azureshares)
}
```

`main.tf` contents:
```hcl
terraform {
  required_providers {
    validation = {
      source  = "tlkamp/validation"
      version = "~> 1.0"
    }
  }
}



module "testing" {
  source = "./modules/repro"

  azureshares = ["1", "2"]
}
```

Output results:

![image](https://github.com/tlkamp/terraform-provider-validation/assets/18516698/9fe439b8-5413-43b3-b2f5-b30c5d4a069e)

**Comment by finkinfridom** [comment]
Thanks for the additional explanation.
I may think that our scenario has an additional complexity where 

```
module "testing" {
  source = "./modules/repro"

  azureshares = ["1", "2"]
}
```

is

```
module "testing" {
  source = "./modules/repro"
  count = var.is_enabled ? 1 :0
  azureshares = ["1", "2"]
}
```

that may require additional dependency to Terraform.
I'll try to run a simple test on my end too to reduce the complexity and find out why our behavior differs from yours.
