### ISSUE TITLE
Missing License Configuration

### ISSUE THREAD

**Issue by leighpascoe** [tlkamp/terraform-provider-validation#9]
The repository is missing a license configuration. This means it [defaults to copyright](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license). Others can't use, compile, build, or modify the code.
According to [Hashicorp](https://github.com/hashicorp/terraform-provider-scaffolding-framework), they recommend using a MPL-2.0 license license.

Would you be able to add a license so we can help develop your code?

**Comment by tlkamp** [comment]
Sure, I'll get to that later today.
